// <auto-generated />
namespace AsmFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class f12xx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(f12xx));
        
        string IMigrationMetadata.Id
        {
            get { return "202008250713170_f12xx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
